services:
  - type: web
    name: disc-entr
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd disc_entr_project && gunicorn disc_entr_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: "366536653665"
      - key: DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.11.0"
